name:                coinsyde
version:             0.3.0.0
github:              "forsyde/coinsyde"
license:             BSD3
author:              "ugeorge"
maintainer:          "ugeorge@kth.se"
copyright:           "2019-2020 George Ungureanu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/coinsyde#readme>

# flags:
#   dynamic:
#     description: Dynamically load library files.
#     manual: false
#     default: true

dependencies:
- base >= 4.7 && < 5
- binary <= 0.8.8.0
- HsYAML
- text
- time
- mtl
- hashable
- containers
- unordered-containers
# for documentation generation
- pandoc-types >= 1.20
- aeson
# I/O utilities
- pretty-simple >= 3
- filepath
- process
- bytestring >= 0.10
- directory >= 1.2

library:
  source-dirs: src
  
executables:
  coinsyde:
    main:                CLI.hs
    source-dirs:         app
    ghc-options:
    - -main-is           CLI
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coinsyde

# tests:
#   f2c-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - coinsyde
