name:                coinsyde
version:             0.2.0.0
github:              "githubuser/coinsyde"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/coinsyde#readme>

# flags:
#   dynamic:
#     description: Dynamically load library files.
#     manual: false
#     default: true

dependencies:
- base >= 4.7 && < 5
- xml
- text
- containers
- parsec
- prettyprinter
- pretty-simple >= 3
- filepath
- bytestring >= 0.10
- directory >= 1.2
- binary
- deepseq
- aeson
- yaml
- vector
- unordered-containers
# when:
# - condition: flag(dynamic)
#   dependencies:
#   - ghc
#   - ghc-lib



library:
  source-dirs: src
  
executables:
  f2c:
    main:                F2C.hs
    source-dirs:         app
    ghc-options:
    - -main-is           F2C
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coinsyde

# tests:
#   f2c-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - coinsyde
